name = "QuantumStateTransfer"
uuid = "34a31443-0e20-4b48-9031-55d81b0a9864"
authors = ["Luis M. B. Varona"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
